-- Generated by dots theme import-aether from Omarchy Catppuccin.
-- Not yet wired into dot_config/nvim/lua/plugins/theme.lua.tmpl (that file
-- still selects the folke/tokyonight.nvim family; see
-- docs/aether-theming-integration-proposal.md, Phase 1 nvim item). Kept as a
-- standalone, loadable palette-based colorscheme for manual testing:
--   :lua dofile(".../nvim.lua")
return {
  setup = function()
    vim.o.background = "dark"
    vim.cmd("hi clear")
    if vim.fn.exists("syntax_on") == 1 then
      vim.cmd("syntax reset")
    end
    vim.g.colors_name = "dots-omarchy-catppuccin"

    local c = {
      bg = "#1e1e2e",
      bg_dark = "#161622",
      bg_light = "#313244",
      fg = "#cdd6f4",
      fg_dim = "#6c7086",
      accent = "#89b4fa",
      muted = "#585b70",
      selection = "#45475a",
      red = "#f38ba8",
      yellow = "#f9e2af",
      orange = "#f6b6ab",
      green = "#a6e3a1",
      cyan = "#94e2d5",
      blue = "#89b4fa",
      magenta = "#f5c2e7",
    }

    local hi = function(group, opts)
      vim.api.nvim_set_hl(0, group, opts)
    end

    hi("Normal", { fg = c.fg, bg = c.bg })
    hi("NormalFloat", { fg = c.fg, bg = c.bg_dark })
    hi("Comment", { fg = c.muted, italic = true })
    hi("Constant", { fg = c.orange })
    hi("String", { fg = c.green })
    hi("Identifier", { fg = c.fg })
    hi("Function", { fg = c.blue })
    hi("Statement", { fg = c.magenta })
    hi("Keyword", { fg = c.magenta })
    hi("Type", { fg = c.yellow })
    hi("Special", { fg = c.cyan })
    hi("Underlined", { fg = c.blue, underline = true })
    hi("Error", { fg = c.bg, bg = c.red })
    hi("Todo", { fg = c.bg, bg = c.yellow })
    hi("LineNr", { fg = c.muted })
    hi("CursorLine", { bg = c.bg_light })
    hi("CursorLineNr", { fg = c.accent })
    hi("Visual", { bg = c.selection })
    hi("Search", { fg = c.bg, bg = c.yellow })
    hi("Pmenu", { fg = c.fg, bg = c.bg_dark })
    hi("PmenuSel", { fg = c.bg, bg = c.accent })
    hi("StatusLine", { fg = c.fg, bg = c.bg_dark })
    hi("StatusLineNC", { fg = c.fg_dim, bg = c.bg_dark })
    hi("DiffAdd", { fg = c.green, bg = c.bg_dark })
    hi("DiffDelete", { fg = c.red, bg = c.bg_dark })
    hi("DiffChange", { fg = c.blue, bg = c.bg_dark })
  end,
}
