#!/usr/bin/env bash
# 75-tool-paths.sh -- PATH entries and shell completions for agent tooling
# (Codex, opencode, grok) that their installers append to the rc files.
# Centralized here so ~/.bashrc and ~/.zshrc stay pure loaders (AGENTS.md §6)
# and the entries are de-duplicated via _path_prepend (00-env.sh).
#
# Sourced by both shells; the grok bash completion is bash-only.

_path_prepend "$HOME/.local/bin"
_path_prepend "$HOME/.opencode/bin"
_path_prepend "$HOME/.grok/bin"
export PATH

if [ "$SHELL_KIND" = bash ] && [ -r "$HOME/.grok/completions/bash/grok.bash" ]; then
  # shellcheck disable=SC1090  # generated by the grok installer at runtime.
  source "$HOME/.grok/completions/bash/grok.bash"
fi
