mode = "dark"

accent = "#f451d3"
selection = "#511a3d"
muted = "#7d5952"

background = "#110402"
dark_background = "#0d0302"
darker_background = "#090201"
lighter_background = "#200e0c"

foreground = "#f0e5e3"
dark_foreground = "#a29694"
light_foreground = "#d4c7c5"
bright_foreground = "#fdf9f8"

hyprland_active_border = "rgba(17e8d9ee) rgba(f451d3ee) 45deg"
hyprland_inactive_border = "rgba(7d5952aa)"

red = "#fe3f50"
yellow = "#ffe5b3"
orange = "#ffa367"
green = "#11e97e"
cyan = "#17e8d9"
blue = "#387eff"
magenta = "#f451d3"
brown = "#805234"

bright_red = "#ff8988"
bright_yellow = "#fef8eb"
bright_green = "#9cfeba"
bright_cyan = "#a5fff4"
bright_blue = "#71a3fd"
bright_magenta = "#ff92e4"
