[tools]
bun = "latest"
chezmoi = "latest"
claude = "latest"
codex = "latest"
copilot = "latest"
gh = "latest"
go = "1.26.5"
node = "latest"
"npm:playwright" = "latest"
opencode = "latest"
pnpm = "latest"
python = "3.12.13"
ruby = "latest"
terraform = "latest"
tflint = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]
compile = false
