-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Acer Technologies XF270HU T78AA0018521",
  mode = "2560x1440@59.95",
  position = "0x0",
  scale = 1.25,
  transform = 2,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Lenovo Group Limited LEN T32p-20 VNA4Y7F8",
  mode = "3840x2160@60.00",
  position = "2048x1152",
  scale = 1.875,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:LG Electronics LG ULTRAGEAR 310NTXR91338",
  mode = "2560x1440@239.97",
  position = "0x1152",
  scale = 1.25,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
