$color = rgba(6, 9, 18, 1)
$inner_color = rgba(6, 9, 18, 0.66)
$outer_color = rgba(141, 113, 140, 1)
$font_color = rgba(149, 154, 164, 1)
$placeholder_color = rgba(149, 154, 164, 0.7)
$check_color = rgba(80, 131, 129, 1)
