-- Generated by dots theme import-aether from Omarchy Everforest.
-- Not yet wired into dot_config/nvim/lua/plugins/theme.lua.tmpl (that file
-- still selects the folke/tokyonight.nvim family; see
-- docs/aether-theming-integration-proposal.md, Phase 1 nvim item). Kept as a
-- standalone, loadable palette-based colorscheme for manual testing:
--   :lua dofile(".../nvim.lua")
return {
  setup = function()
    vim.o.background = "dark"
    vim.cmd("hi clear")
    if vim.fn.exists("syntax_on") == 1 then
      vim.cmd("syntax reset")
    end
    vim.g.colors_name = "dots-omarchy-everforest"

    local c = {
      bg = "#2d353b",
      bg_dark = "#21272c",
      bg_light = "#343f44",
      fg = "#d3c6aa",
      fg_dim = "#4f585e",
      accent = "#7fbbb3",
      muted = "#475258",
      selection = "#3d484d",
      red = "#e67e80",
      yellow = "#dbbc7f",
      orange = "#e09d7f",
      green = "#a7c080",
      cyan = "#83c092",
      blue = "#7fbbb3",
      magenta = "#d699b6",
    }

    local hi = function(group, opts)
      vim.api.nvim_set_hl(0, group, opts)
    end

    hi("Normal", { fg = c.fg, bg = c.bg })
    hi("NormalFloat", { fg = c.fg, bg = c.bg_dark })
    hi("Comment", { fg = c.muted, italic = true })
    hi("Constant", { fg = c.orange })
    hi("String", { fg = c.green })
    hi("Identifier", { fg = c.fg })
    hi("Function", { fg = c.blue })
    hi("Statement", { fg = c.magenta })
    hi("Keyword", { fg = c.magenta })
    hi("Type", { fg = c.yellow })
    hi("Special", { fg = c.cyan })
    hi("Underlined", { fg = c.blue, underline = true })
    hi("Error", { fg = c.bg, bg = c.red })
    hi("Todo", { fg = c.bg, bg = c.yellow })
    hi("LineNr", { fg = c.muted })
    hi("CursorLine", { bg = c.bg_light })
    hi("CursorLineNr", { fg = c.accent })
    hi("Visual", { bg = c.selection })
    hi("Search", { fg = c.bg, bg = c.yellow })
    hi("Pmenu", { fg = c.fg, bg = c.bg_dark })
    hi("PmenuSel", { fg = c.bg, bg = c.accent })
    hi("StatusLine", { fg = c.fg, bg = c.bg_dark })
    hi("StatusLineNC", { fg = c.fg_dim, bg = c.bg_dark })
    hi("DiffAdd", { fg = c.green, bg = c.bg_dark })
    hi("DiffDelete", { fg = c.red, bg = c.bg_dark })
    hi("DiffChange", { fg = c.blue, bg = c.bg_dark })
  end,
}
