# Background and foreground colors
background = #000000
foreground = #e9f4ff

# Standard colors
palette = 0=#000000
palette = 1=#a189a8
palette = 2=#a4c2e9
palette = 3=#ffdcff
palette = 4=#7b789e
palette = 5=#b19fce
palette = 6=#c1d5ff
palette = 7=#e9f4ff

# Bright colors
palette = 8=#686163
palette = 9=#ba9cc2
palette = 10=#b2daff
palette = 11=#ffdaff
palette = 12=#8f8cbb
palette = 13=#c9b2ee
palette = 14=#d2ecff
palette = 15=#f5f3ff
