background            #000000
foreground            #e9f4ff

# black
color0  #000000
color8  #686163

# red
color1  #a189a8
color9  #ba9cc2

# green
color2  #a4c2e9
color10 #b2daff

# yellow
color3  #ffdcff
color11 #ffdaff

# blue
color4  #7b789e
color12 #8f8cbb

# magenta
color5  #b19fce
color13 #c9b2ee

#cyan
color6  #c1d5ff
color14 #d2ecff

#white
color7  #e9f4ff
color15 #f5f3ff


