#!/usr/bin/env python3
"""Regenerate the `## 📂 Repository Structure` tree in README.md.

Replaces the block between the BEGIN/END markers with an accurate tree built
from `git ls-files` (tracked source entries). Run this after adding/removing
dotfiles so the README structure can never drift.

Usage:
    python3 docs/generate_readme_tree.py            # in the chezmoi source root
    python3 docs/generate_readme_tree.py --check    # non-zero exit if stale

Meta/repo-only entries (README.md, docs/, the submodule, package.json, …) are
excluded: they are git material, not home-dir dotfiles. If you add a new
top-level meta path, add it to SKIP so the tree stays focused on dotfiles.
"""

import argparse
import subprocess
import sys
from pathlib import Path


README = Path(__file__).resolve().parent.parent / "README.md"
BEGIN = "<!-- BEGIN REPO TREE (generated by docs/generate_readme_tree.py) -->"
END = "<!-- END REPO TREE -->"

# Paths that are repository/git material rather than dotfiles; excluded from the
# tree so it reflects what chezmoi actually manages.
SKIP = (
    "README.md",
    "AGENTS.md",
    "INDEX.md",
    "INDEX.json",
    "setup.sh",
    "package.json",
    "bun.lock",
    ".github/",
    "docs/",
    "Documents/",
    ".gitmodules",
    ".gitignore",
    ".gitleaksignore",
    ".gitleaks.toml",
    "dotfiles-showcase",
    "to-questionnaire-",
)

# Subtrees rendered as a single annotated line instead of being expanded.
# They are real managed dotfiles (so not SKIPped), but enumerate homogeneous
# families that drown the tree at full depth. The line notes the file count
# and (where helpful) points at the manifest that owns the family.
COLLAPSED = {
    "dot_hermes/skills": "skills/ ({n} files across {groups} skill groups — see .chezmoidata/hermes_skills.yaml)",
    ".chezmoitemplates/themes": "themes/ ({n} files across {groups} themes — see .chezmoidata/themes.yaml)",
    ".chezmoitemplates/aether-adapters": "aether-adapters/ ({n} files — per-tool theme adapters)",
    "theme-assets": "theme-assets/ ({n} files across {groups} wallpaper sets)",
}


# Top-level `run_*` apply hooks share one naming grammar
# (trigger_phase_NN-name) and INDEX.md already tabulates their trigger/phase
# semantics, so the tree lists them as one summary line with a pointer.
RUN_HOOKS_NOTE = "run_* apply hooks ({n} — see INDEX.md § Apply hooks for trigger/phase)"

# Leaf-name families collapsed to one summary line when the whole family
# lives in the same directory: per-agent usage collectors differ only by
# agent name, so the tree keeps a representative count instead of N rows.
FAMILY_COLLAPSE = {
    "dot_local/bin": (
        "executable_omarchy-agent-usage-",
        "executable_omarchy-agent-usage-<agent>.tmpl ({n} agents)",
    ),
    "dot_config/systemd/user": (
        "omarchy-",
        "omarchy-* units ({n} — scrapers, relays, daemons)",
    ),
}


def tracked(limit):
    out = subprocess.check_output(["git", "ls-files"]).decode().splitlines()
    files = []
    collapsed = {}
    families = {}
    for path in out:
        if any(path == s or path.startswith(s) for s in SKIP):
            continue
        for prefix, note in COLLAPSED.items():
            if path.startswith(prefix + "/") or path == prefix:
                n, g = collapsed.get(prefix, (0, set()))
                collapsed[prefix] = (n + 1, g | {path[len(prefix) + 1:].split("/")[0]})
                break
        else:
            # run_* hooks: all top-level .sh.tmpl, counted and summarized.
            if "/" not in path and path.startswith("run_") and path.endswith(".sh.tmpl"):
                n = families.get("run_*", 0) + 1
                families["run_*"] = n
                continue
            head, _, leaf = path.rpartition("/")
            fam = FAMILY_COLLAPSE.get(head)
            if fam and leaf.startswith(fam[0]):
                entry = families.get(head)
                if entry is None:
                    families[head] = [1, fam[1]]
                else:
                    entry[0] += 1
                continue
            parts = path.split("/")
            if limit and len(parts) > limit:
                parts = parts[:limit]
                # collapse deeper nesting under its parent directory
                path = "/".join(parts) + "/…"
            files.append(parts)
    for prefix, (n, groups) in collapsed.items():
        note = COLLAPSED[prefix].format(n=n, groups=len(groups))
        # anchor the summary under the prefix's parent (e.g. dot_hermes/)
        head, _, tail = prefix.rpartition("/")
        files.append((*(head.split("/") if head else []), note))
    if "run_*" in families:
        files.append((RUN_HOOKS_NOTE.format(n=families["run_*"]),))
    for head, value in families.items():
        if head == "run_*":
            continue
        n, note = value
        files.append((*(head.split("/") if head else []), note.format(n=n)))
    return files


def build(parts_list):
    def insert(tree, parts):
        node = tree
        for part in parts:
            if part not in node:
                node[part] = {}
            node = node[part]

    root = {}
    for parts in parts_list:
        insert(root, parts)
    return root


def render_children(node, prefix):
    lines = []
    entries = sorted(node.items(), key=lambda kv: (kv[0].endswith("/"), kv[0]))
    count = len(entries)
    for i, (name, child) in enumerate(entries):
        last = i == count - 1
        branch = "└── " if last else "├── "
        lines.append(prefix + branch + name)
        if child:
            cont = "    " if last else "│   "
            lines.extend(render_children(child, prefix + cont))
    return lines


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if README is stale")
    ap.add_argument("--limit", type=int, default=None, help="max path depth")
    args = ap.parse_args()

    root = build(tracked(args.limit))
    body = "\n".join(render_children(root, ""))
    block = f"```text\n.\n{body}\n```\n"

    text = README.read_text()
    if BEGIN not in text or END not in text:
        sys.exit(f"ERROR: {README} is missing the tree markers ({BEGIN}…{END}).")
    start = text.index(BEGIN) + len(BEGIN)
    end = text.index(END)
    updated = text[:start] + "\n" + block + text[end:]

    if args.check:
        if updated == text:
            print("README tree is up to date.")
            return
        print("README tree is stale; run docs/generate_readme_tree.py", file=sys.stderr)
        sys.exit(1)

    README.write_text(updated)
    print(f"Updated {README}")


if __name__ == "__main__":
    main()
