#!/usr/bin/env python3
"""Regenerate the `## 📂 Repository Structure` tree in README.md.

Replaces the block between the BEGIN/END markers with an accurate tree built
from `git ls-files` (tracked source entries). Run this after adding/removing
dotfiles so the README structure can never drift.

Usage:
    python3 docs/generate_readme_tree.py            # in the chezmoi source root
    python3 docs/generate_readme_tree.py --check    # non-zero exit if stale

Meta/repo-only entries (README.md, docs/, the submodule, package.json, …) are
excluded: they are git material, not home-dir dotfiles. If you add a new
top-level meta path, add it to SKIP so the tree stays focused on dotfiles.
"""

import argparse
import subprocess
import sys
from pathlib import Path


README = Path(__file__).resolve().parent.parent / "README.md"
BEGIN = "<!-- BEGIN REPO TREE (generated by docs/generate_readme_tree.py) -->"
END = "<!-- END REPO TREE -->"

# Paths that are repository/git material rather than dotfiles; excluded from the
# tree so it reflects what chezmoi actually manages.
SKIP = (
    "README.md",
    "AGENTS.md",
    "INDEX.md",
    "INDEX.json",
    "package.json",
    "bun.lock",
    ".github/",
    "docs/",
    "Documents/",
    ".gitmodules",
    "dotfiles-showcase",
    "to-questionnaire-",
)


def tracked(limit):
    out = subprocess.check_output(["git", "ls-files"]).decode().splitlines()
    files = []
    for path in out:
        if any(path == s or path.startswith(s) for s in SKIP):
            continue
        parts = path.split("/")
        if limit and len(parts) > limit:
            parts = parts[:limit]
            # collapse deeper nesting under its parent directory
            path = "/".join(parts) + "/…"
        files.append(parts)
    return files


def build(parts_list):
    def insert(tree, parts):
        node = tree
        for part in parts:
            if part not in node:
                node[part] = {}
            node = node[part]

    root = {}
    for parts in parts_list:
        insert(root, parts)
    return root


def render_children(node, prefix):
    lines = []
    entries = sorted(node.items(), key=lambda kv: (kv[0].endswith("/"), kv[0]))
    count = len(entries)
    for i, (name, child) in enumerate(entries):
        last = i == count - 1
        branch = "└── " if last else "├── "
        lines.append(prefix + branch + name)
        if child:
            cont = "    " if last else "│   "
            lines.extend(render_children(child, prefix + cont))
    return lines


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if README is stale")
    ap.add_argument("--limit", type=int, default=None, help="max path depth")
    args = ap.parse_args()

    root = build(tracked(args.limit))
    body = "\n".join(render_children(root, ""))
    block = f"```text\n.\n{body}\n```\n"

    text = README.read_text()
    if BEGIN not in text or END not in text:
        sys.exit(f"ERROR: {README} is missing the tree markers ({BEGIN}…{END}).")
    start = text.index(BEGIN) + len(BEGIN)
    end = text.index(END)
    updated = text[:start] + "\n" + block + text[end:]

    if args.check:
        if updated == text:
            print("README tree is up to date.")
            return
        print("README tree is stale; run docs/generate_readme_tree.py", file=sys.stderr)
        sys.exit(1)

    README.write_text(updated)
    print(f"Updated {README}")


if __name__ == "__main__":
    main()
